name = "Erzya"
version = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Erzya spellchecker"
myv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Erzya, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
myv = "TRANSLATE: A spellchecker for Erzya, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.myv"

[windows]
system_product_code = "{C58DC9DD-1E95-4A3A-98F6-7C3EF36C6A5E}_is1"
legacy_product_codes = [
    { value = "1C7505CF-C679-4002-87CC-342AF57E22AC", kind = "nsis" },
    { value = "43E775DA-CC5E-41DA-955D-DB42E49303EC", kind = "nsis" }
]
