name = "Erzya"
version = "0.1.0"

[macos]
system_pkg_id = "no.divvun.MacDivvun.myv"

[windows]
system_product_code = "43E775DA-CC5E-41DA-955D-DB42E49303EC"
msoffice_product_code = "1C7505CF-C679-4002-87CC-342AF57E22AC"
