template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "erzy1239"
__REPO__ = "lang-myv"
__UND2C__ = "myv"
__UNDEFINED__ = "Erzya"
__UND__ = "myv"
