template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "erzy1239"
__REPO__ = "lang-myv"
__UND2C__ = "myv"
__UNDEFINED__ = "Erzya"
__UND__ = "myv"
