template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "erzy1239"
__REPO__ = "lang-myv"
__UND2C__ = "myv"
__UNDEFINED__ = "Erzya"
__UND__ = "myv"
