[package]
name = "myv"
human_name = "Erzya"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.myv]
filename = "myv-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-myv"
platform = "windows"
uuid = "43E775DA-CC5E-41DA-955D-DB42E49303EC"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.myv"
package = "speller-myv"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-myv-mso"
platform = "windows"
uuid = "1C7505CF-C679-4002-87CC-342AF57E22AC"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-myv"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
